# AWS-specific options.
aws:

  queueUrl: https://sqs.us-east-1.amazonaws.com/860114833029/smoketurner-queue
  region: us-east-1

# Swagger-specific options.
swagger:

  resourcePackage: com.smoketurner.pipeline.application.resources
  title: Pipeline API
  version: v1
  description: Pipeline service API
  contact: jplock@smoketurner.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

# HTTP-specific options.
server:

  gzip:
    enabled: false

  applicationConnectors:
    - type: http
      port: 8080
  
  adminConnectors:
    - type: http
      port: 8180

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout
#      - type: file
#        currentLogFilename: /var/log/pipeline/requests.log
#        threshold: ALL
#        archive: true
#        archivedLogFilenamePattern: /var/log/pipeline/requests-%d.log
#        archivedFileCount: 5
#        timeZone: UTC

logging:
  level: INFO
  loggers:
    com.smoketurner.pipeline: DEBUG
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
#    - type: file
#      currentLogFilename: /var/log/pipeline/app.log
#      threshold: ALL
#      archive: true
#      archivedLogFilenamePattern: /var/log/pipeline/app-%d.log
#      archivedFileCount: 5
#      timeZone: UTC
