# {{{project.name}}} - {{{project.description}}}
# {{{project.artifactId}}} configuration

# AWS-specific options.
aws:

  queueUrl: https://sqs.us-east-1.amazonaws.com/860114833029/smoketurner-queue

# Swagger-specific options.
swagger:

  resourcePackage: com.smoketurner.pipline.application.resources
  title: Pipeline API
  version: v1
  description: Pipeline service API
  contact: jplock@smoketurner.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

# HTTP-specific options.
server:

  gzip:
    enabled: false

  applicationConnectors:
    - type: http
      port: {{{dw.httpPort}}}
  
  adminConnectors:
    - type: http
      port: {{{dw.httpAdminPort}}}

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout
      - type: file
        currentLogFilename: "{{{path.logDirectory}}}/requests.log"
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: "{{{path.logDirectory}}}/requests-%d.log"
        archivedFileCount: 5
        timeZone: UTC

logging:
  level: INFO
  loggers:
    com.smoketurner.pipeline: DEBUG
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: "{{{path.logDirectory}}}/app.log"
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: "{{{path.logDirectory}}}/app-%d.log"
      archivedFileCount: 5
      timeZone: UTC
